name: Action two workflow
on: 
    push:
        branches: [ "main" ]

jobs:
    Build_Test:
        runs-on: ubuntu-latest
        steps:
            - name: step1 - download code
              uses: actions/checkout@v3
            - name: step2 - install nodejs
              uses: actions/setup-node@v3
              with:
                node-version: 16
            - name: step3 - install dependencies
              run: npm ci
            - name: step4 - test app
              run: npm test

